// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXzF1ObyWkWVAZ7U6fVjauNmzBoAUCGqo',
    appId: '1:99718587655:android:b99f6b0d7ff9b84fb711a2',
    messagingSenderId: '99718587655',
    projectId: 'rede-vizinha',
    databaseURL: 'https://rede-vizinha-default-rtdb.firebaseio.com',
    storageBucket: 'rede-vizinha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-24G0JxCfRegC-GLEZJ3pow2BGhIA8M8',
    appId: '1:99718587655:ios:ed8c3b3aa32f96f6b711a2',
    messagingSenderId: '99718587655',
    projectId: 'rede-vizinha',
    databaseURL: 'https://rede-vizinha-default-rtdb.firebaseio.com',
    storageBucket: 'rede-vizinha.firebasestorage.app',
    iosBundleId: 'com.example.redeVizinhaApp',
  );
}
